/*
 * This file is generated by jOOQ.
 */
package ch.rasc.realworld.db;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import ch.rasc.realworld.db.tables.AppUser;
import ch.rasc.realworld.db.tables.Article;
import ch.rasc.realworld.db.tables.ArticleFavorite;
import ch.rasc.realworld.db.tables.ArticleTag;
import ch.rasc.realworld.db.tables.Comment;
import ch.rasc.realworld.db.tables.Follow;
import ch.rasc.realworld.db.tables.Tag;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultSchema extends SchemaImpl {

	private static final long serialVersionUID = 1L;

	/**
	 * The reference instance of <code>DEFAULT_SCHEMA</code>
	 */
	public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

	/**
	 * The table <code>APP_USER</code>.
	 */
	public final AppUser APP_USER = AppUser.APP_USER;

	/**
	 * The table <code>ARTICLE</code>.
	 */
	public final Article ARTICLE = Article.ARTICLE;

	/**
	 * The table <code>ARTICLE_FAVORITE</code>.
	 */
	public final ArticleFavorite ARTICLE_FAVORITE = ArticleFavorite.ARTICLE_FAVORITE;

	/**
	 * The table <code>ARTICLE_TAG</code>.
	 */
	public final ArticleTag ARTICLE_TAG = ArticleTag.ARTICLE_TAG;

	/**
	 * The table <code>COMMENT</code>.
	 */
	public final Comment COMMENT = Comment.COMMENT;

	/**
	 * The table <code>FOLLOW</code>.
	 */
	public final Follow FOLLOW = Follow.FOLLOW;

	/**
	 * The table <code>TAG</code>.
	 */
	public final Tag TAG = Tag.TAG;

	/**
	 * No further instances allowed
	 */
	private DefaultSchema() {
		super("", null);
	}

	@Override
	public Catalog getCatalog() {
		return DefaultCatalog.DEFAULT_CATALOG;
	}

	@Override
	public final List<Table<?>> getTables() {
		return Arrays.asList(AppUser.APP_USER, Article.ARTICLE,
				ArticleFavorite.ARTICLE_FAVORITE, ArticleTag.ARTICLE_TAG, Comment.COMMENT,
				Follow.FOLLOW, Tag.TAG);
	}
}
