/*
 * This file is generated by jOOQ.
 */
package ch.rasc.realworld.db;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;

import ch.rasc.realworld.db.tables.AppUser;
import ch.rasc.realworld.db.tables.Article;
import ch.rasc.realworld.db.tables.ArticleFavorite;
import ch.rasc.realworld.db.tables.ArticleTag;
import ch.rasc.realworld.db.tables.Comment;
import ch.rasc.realworld.db.tables.Follow;
import ch.rasc.realworld.db.tables.Tag;

/**
 * A class modelling indexes of tables of the <code></code> schema.
 */
@Generated(value = { "http://www.jooq.org", "jOOQ version:3.11.11" },
		comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

	// -------------------------------------------------------------------------
	// INDEX definitions
	// -------------------------------------------------------------------------

	public static final Index CONSTRAINT_INDEX_7 = Indexes0.CONSTRAINT_INDEX_7;
	public static final Index CONSTRAINT_INDEX_76 = Indexes0.CONSTRAINT_INDEX_76;
	public static final Index PRIMARY_KEY_7 = Indexes0.PRIMARY_KEY_7;
	public static final Index CONSTRAINT_INDEX_F = Indexes0.CONSTRAINT_INDEX_F;
	public static final Index CONSTRAINT_INDEX_FF = Indexes0.CONSTRAINT_INDEX_FF;
	public static final Index PRIMARY_KEY_F = Indexes0.PRIMARY_KEY_F;
	public static final Index CONSTRAINT_INDEX_B = Indexes0.CONSTRAINT_INDEX_B;
	public static final Index CONSTRAINT_INDEX_B0 = Indexes0.CONSTRAINT_INDEX_B0;
	public static final Index PRIMARY_KEY_B = Indexes0.PRIMARY_KEY_B;
	public static final Index CONSTRAINT_INDEX_B1 = Indexes0.CONSTRAINT_INDEX_B1;
	public static final Index CONSTRAINT_INDEX_B12 = Indexes0.CONSTRAINT_INDEX_B12;
	public static final Index PRIMARY_KEY_B1 = Indexes0.PRIMARY_KEY_B1;
	public static final Index CONSTRAINT_INDEX_6 = Indexes0.CONSTRAINT_INDEX_6;
	public static final Index CONSTRAINT_INDEX_63 = Indexes0.CONSTRAINT_INDEX_63;
	public static final Index PRIMARY_KEY_6 = Indexes0.PRIMARY_KEY_6;
	public static final Index CONSTRAINT_INDEX_7B = Indexes0.CONSTRAINT_INDEX_7B;
	public static final Index CONSTRAINT_INDEX_7BF = Indexes0.CONSTRAINT_INDEX_7BF;
	public static final Index PRIMARY_KEY_7B = Indexes0.PRIMARY_KEY_7B;
	public static final Index PRIMARY_KEY_1 = Indexes0.PRIMARY_KEY_1;

	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class Indexes0 {
		public static Index CONSTRAINT_INDEX_7 = Internal.createIndex(
				"CONSTRAINT_INDEX_7", AppUser.APP_USER,
				new OrderField[] { AppUser.APP_USER.USERNAME }, true);
		public static Index CONSTRAINT_INDEX_76 = Internal.createIndex(
				"CONSTRAINT_INDEX_76", AppUser.APP_USER,
				new OrderField[] { AppUser.APP_USER.EMAIL }, true);
		public static Index PRIMARY_KEY_7 = Internal.createIndex("PRIMARY_KEY_7",
				AppUser.APP_USER, new OrderField[] { AppUser.APP_USER.ID }, true);
		public static Index CONSTRAINT_INDEX_F = Internal.createIndex(
				"CONSTRAINT_INDEX_F", Article.ARTICLE,
				new OrderField[] { Article.ARTICLE.SLUG }, true);
		public static Index CONSTRAINT_INDEX_FF = Internal.createIndex(
				"CONSTRAINT_INDEX_FF", Article.ARTICLE,
				new OrderField[] { Article.ARTICLE.USER_ID }, false);
		public static Index PRIMARY_KEY_F = Internal.createIndex("PRIMARY_KEY_F",
				Article.ARTICLE, new OrderField[] { Article.ARTICLE.ID }, true);
		public static Index CONSTRAINT_INDEX_B = Internal.createIndex(
				"CONSTRAINT_INDEX_B", ArticleFavorite.ARTICLE_FAVORITE,
				new OrderField[] { ArticleFavorite.ARTICLE_FAVORITE.ARTICLE_ID }, false);
		public static Index CONSTRAINT_INDEX_B0 = Internal.createIndex(
				"CONSTRAINT_INDEX_B0", ArticleFavorite.ARTICLE_FAVORITE,
				new OrderField[] { ArticleFavorite.ARTICLE_FAVORITE.USER_ID }, false);
		public static Index PRIMARY_KEY_B = Internal.createIndex("PRIMARY_KEY_B",
				ArticleFavorite.ARTICLE_FAVORITE,
				new OrderField[] { ArticleFavorite.ARTICLE_FAVORITE.ARTICLE_ID,
						ArticleFavorite.ARTICLE_FAVORITE.USER_ID },
				true);
		public static Index CONSTRAINT_INDEX_B1 = Internal.createIndex(
				"CONSTRAINT_INDEX_B1", ArticleTag.ARTICLE_TAG,
				new OrderField[] { ArticleTag.ARTICLE_TAG.ARTICLE_ID }, false);
		public static Index CONSTRAINT_INDEX_B12 = Internal.createIndex(
				"CONSTRAINT_INDEX_B12", ArticleTag.ARTICLE_TAG,
				new OrderField[] { ArticleTag.ARTICLE_TAG.TAG_ID }, false);
		public static Index PRIMARY_KEY_B1 = Internal.createIndex("PRIMARY_KEY_B1",
				ArticleTag.ARTICLE_TAG,
				new OrderField[] { ArticleTag.ARTICLE_TAG.ARTICLE_ID,
						ArticleTag.ARTICLE_TAG.TAG_ID },
				true);
		public static Index CONSTRAINT_INDEX_6 = Internal.createIndex(
				"CONSTRAINT_INDEX_6", Comment.COMMENT,
				new OrderField[] { Comment.COMMENT.USER_ID }, false);
		public static Index CONSTRAINT_INDEX_63 = Internal.createIndex(
				"CONSTRAINT_INDEX_63", Comment.COMMENT,
				new OrderField[] { Comment.COMMENT.ARTICLE_ID }, false);
		public static Index PRIMARY_KEY_6 = Internal.createIndex("PRIMARY_KEY_6",
				Comment.COMMENT, new OrderField[] { Comment.COMMENT.ID }, true);
		public static Index CONSTRAINT_INDEX_7B = Internal.createIndex(
				"CONSTRAINT_INDEX_7B", Follow.FOLLOW,
				new OrderField[] { Follow.FOLLOW.USER_ID }, false);
		public static Index CONSTRAINT_INDEX_7BF = Internal.createIndex(
				"CONSTRAINT_INDEX_7BF", Follow.FOLLOW,
				new OrderField[] { Follow.FOLLOW.FOLLOW_ID }, false);
		public static Index PRIMARY_KEY_7B = Internal.createIndex("PRIMARY_KEY_7B",
				Follow.FOLLOW,
				new OrderField[] { Follow.FOLLOW.USER_ID, Follow.FOLLOW.FOLLOW_ID },
				true);
		public static Index PRIMARY_KEY_1 = Internal.createIndex("PRIMARY_KEY_1", Tag.TAG,
				new OrderField[] { Tag.TAG.ID }, true);
	}
}
