/*
 * This file is generated by jOOQ.
 */
package ch.rasc.realworld.db;

import javax.annotation.Generated;

import ch.rasc.realworld.db.tables.AppUser;
import ch.rasc.realworld.db.tables.Article;
import ch.rasc.realworld.db.tables.ArticleFavorite;
import ch.rasc.realworld.db.tables.ArticleTag;
import ch.rasc.realworld.db.tables.Comment;
import ch.rasc.realworld.db.tables.Follow;
import ch.rasc.realworld.db.tables.Tag;

/**
 * Convenience access to all tables in
 */
@Generated(value = { "http://www.jooq.org", "jOOQ version:3.11.11" },
		comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table <code>APP_USER</code>.
	 */
	public static final AppUser APP_USER = ch.rasc.realworld.db.tables.AppUser.APP_USER;

	/**
	 * The table <code>ARTICLE</code>.
	 */
	public static final Article ARTICLE = ch.rasc.realworld.db.tables.Article.ARTICLE;

	/**
	 * The table <code>ARTICLE_FAVORITE</code>.
	 */
	public static final ArticleFavorite ARTICLE_FAVORITE = ch.rasc.realworld.db.tables.ArticleFavorite.ARTICLE_FAVORITE;

	/**
	 * The table <code>ARTICLE_TAG</code>.
	 */
	public static final ArticleTag ARTICLE_TAG = ch.rasc.realworld.db.tables.ArticleTag.ARTICLE_TAG;

	/**
	 * The table <code>COMMENT</code>.
	 */
	public static final Comment COMMENT = ch.rasc.realworld.db.tables.Comment.COMMENT;

	/**
	 * The table <code>FOLLOW</code>.
	 */
	public static final Follow FOLLOW = ch.rasc.realworld.db.tables.Follow.FOLLOW;

	/**
	 * The table <code>TAG</code>.
	 */
	public static final Tag TAG = ch.rasc.realworld.db.tables.Tag.TAG;
}
