version: '3.8'

services:

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: realworld
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"

volumes:
  postgres:
