/*
 * This file is generated by jOOQ.
 */
package ch.rasc.realworld.db.tables;

import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function2;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import ch.rasc.realworld.db.DefaultSchema;
import ch.rasc.realworld.db.Keys;
import ch.rasc.realworld.db.tables.records.ArticleFavoriteRecord;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ArticleFavorite extends TableImpl<ArticleFavoriteRecord> {

	private static final long serialVersionUID = 1L;

	/**
	 * The reference instance of <code>ARTICLE_FAVORITE</code>
	 */
	public static final ArticleFavorite ARTICLE_FAVORITE = new ArticleFavorite();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<ArticleFavoriteRecord> getRecordType() {
		return ArticleFavoriteRecord.class;
	}

	/**
	 * The column <code>ARTICLE_FAVORITE.ARTICLE_ID</code>.
	 */
	public final TableField<ArticleFavoriteRecord, Long> ARTICLE_ID = createField(
			DSL.name("ARTICLE_ID"), SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>ARTICLE_FAVORITE.USER_ID</code>.
	 */
	public final TableField<ArticleFavoriteRecord, Long> USER_ID = createField(
			DSL.name("USER_ID"), SQLDataType.BIGINT.nullable(false), this, "");

	private ArticleFavorite(Name alias, Table<ArticleFavoriteRecord> aliased) {
		this(alias, aliased, null);
	}

	private ArticleFavorite(Name alias, Table<ArticleFavoriteRecord> aliased,
			Field<?>[] parameters) {
		super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
	}

	/**
	 * Create an aliased <code>ARTICLE_FAVORITE</code> table reference
	 */
	public ArticleFavorite(String alias) {
		this(DSL.name(alias), ARTICLE_FAVORITE);
	}

	/**
	 * Create an aliased <code>ARTICLE_FAVORITE</code> table reference
	 */
	public ArticleFavorite(Name alias) {
		this(alias, ARTICLE_FAVORITE);
	}

	/**
	 * Create a <code>ARTICLE_FAVORITE</code> table reference
	 */
	public ArticleFavorite() {
		this(DSL.name("ARTICLE_FAVORITE"), null);
	}

	public <O extends Record> ArticleFavorite(Table<O> child,
			ForeignKey<O, ArticleFavoriteRecord> key) {
		super(child, key, ARTICLE_FAVORITE);
	}

	@Override
	public Schema getSchema() {
		return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
	}

	@Override
	public UniqueKey<ArticleFavoriteRecord> getPrimaryKey() {
		return Keys.CONSTRAINT_B;
	}

	@Override
	public List<ForeignKey<ArticleFavoriteRecord, ?>> getReferences() {
		return Arrays.asList(Keys.CONSTRAINT_B0, Keys.CONSTRAINT_B05);
	}

	private transient Article _article;
	private transient AppUser _appUser;

	/**
	 * Get the implicit join path to the <code>PUBLIC.ARTICLE</code> table.
	 */
	public Article article() {
		if (this._article == null) {
			this._article = new Article(this, Keys.CONSTRAINT_B0);
		}

		return this._article;
	}

	/**
	 * Get the implicit join path to the <code>PUBLIC.APP_USER</code> table.
	 */
	public AppUser appUser() {
		if (this._appUser == null) {
			this._appUser = new AppUser(this, Keys.CONSTRAINT_B05);
		}

		return this._appUser;
	}

	@Override
	public ArticleFavorite as(String alias) {
		return new ArticleFavorite(DSL.name(alias), this);
	}

	@Override
	public ArticleFavorite as(Name alias) {
		return new ArticleFavorite(alias, this);
	}

	@Override
	public ArticleFavorite as(Table<?> alias) {
		return new ArticleFavorite(alias.getQualifiedName(), this);
	}

	/**
	 * Rename this table
	 */
	@Override
	public ArticleFavorite rename(String name) {
		return new ArticleFavorite(DSL.name(name), null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public ArticleFavorite rename(Name name) {
		return new ArticleFavorite(name, null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public ArticleFavorite rename(Table<?> name) {
		return new ArticleFavorite(name.getQualifiedName(), null);
	}

	// -------------------------------------------------------------------------
	// Row2 type methods
	// -------------------------------------------------------------------------

	@Override
	public Row2<Long, Long> fieldsRow() {
		return (Row2) super.fieldsRow();
	}

	/**
	 * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
	 */
	public <U> SelectField<U> mapping(
			Function2<? super Long, ? super Long, ? extends U> from) {
		return convertFrom(Records.mapping(from));
	}

	/**
	 * Convenience mapping calling {@link SelectField#convertFrom(Class, Function)}.
	 */
	public <U> SelectField<U> mapping(Class<U> toType,
			Function2<? super Long, ? super Long, ? extends U> from) {
		return convertFrom(toType, Records.mapping(from));
	}
}
