/*
 * This file is generated by jOOQ.
 */
package ch.rasc.realworld.db.tables;

import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function3;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import ch.rasc.realworld.db.DefaultSchema;
import ch.rasc.realworld.db.Keys;
import ch.rasc.realworld.db.tables.records.FollowRecord;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Follow extends TableImpl<FollowRecord> {

	private static final long serialVersionUID = 1L;

	/**
	 * The reference instance of <code>follow</code>
	 */
	public static final Follow FOLLOW = new Follow();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<FollowRecord> getRecordType() {
		return FollowRecord.class;
	}

	/**
	 * The column <code>follow.id</code>.
	 */
	public final TableField<FollowRecord, Long> ID = createField(DSL.name("id"),
			SQLDataType.BIGINT.nullable(false).identity(true), this, "");

	/**
	 * The column <code>follow.user_id</code>.
	 */
	public final TableField<FollowRecord, Long> USER_ID = createField(DSL.name("user_id"),
			SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>follow.follow_id</code>.
	 */
	public final TableField<FollowRecord, Long> FOLLOW_ID = createField(DSL.name("follow_id"),
			SQLDataType.BIGINT.nullable(false), this, "");

	private Follow(Name alias, Table<FollowRecord> aliased) {
		this(alias, aliased, null);
	}

	private Follow(Name alias, Table<FollowRecord> aliased, Field<?>[] parameters) {
		super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
	}

	/**
	 * Create an aliased <code>follow</code> table reference
	 */
	public Follow(String alias) {
		this(DSL.name(alias), FOLLOW);
	}

	/**
	 * Create an aliased <code>follow</code> table reference
	 */
	public Follow(Name alias) {
		this(alias, FOLLOW);
	}

	/**
	 * Create a <code>follow</code> table reference
	 */
	public Follow() {
		this(DSL.name("follow"), null);
	}

	public <O extends Record> Follow(Table<O> child, ForeignKey<O, FollowRecord> key) {
		super(child, key, FOLLOW);
	}

	@Override
	public Schema getSchema() {
		return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
	}

	@Override
	public Identity<FollowRecord, Long> getIdentity() {
		return (Identity<FollowRecord, Long>) super.getIdentity();
	}

	@Override
	public UniqueKey<FollowRecord> getPrimaryKey() {
		return Keys.CONSTRAINT_B;
	}

	@Override
	public List<ForeignKey<FollowRecord, ?>> getReferences() {
		return Arrays.asList(Keys.FK_FOLLOW_USER, Keys.FK_FOLLOW_FOLLOW_USER);
	}

	private transient AppUser _fkFollowUser;
	private transient AppUser _fkFollowFollowUser;

	/**
	 * Get the implicit join path to the <code>PUBLIC.app_user</code> table, via the
	 * <code>fk_follow_user</code> key.
	 */
	public AppUser fkFollowUser() {
		if (_fkFollowUser == null)
			_fkFollowUser = new AppUser(this, Keys.FK_FOLLOW_USER);

		return _fkFollowUser;
	}

	/**
	 * Get the implicit join path to the <code>PUBLIC.app_user</code> table, via the
	 * <code>fk_follow_follow_user</code> key.
	 */
	public AppUser fkFollowFollowUser() {
		if (_fkFollowFollowUser == null)
			_fkFollowFollowUser = new AppUser(this, Keys.FK_FOLLOW_FOLLOW_USER);

		return _fkFollowFollowUser;
	}

	@Override
	public Follow as(String alias) {
		return new Follow(DSL.name(alias), this);
	}

	@Override
	public Follow as(Name alias) {
		return new Follow(alias, this);
	}

	@Override
	public Follow as(Table<?> alias) {
		return new Follow(alias.getQualifiedName(), this);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Follow rename(String name) {
		return new Follow(DSL.name(name), null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Follow rename(Name name) {
		return new Follow(name, null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Follow rename(Table<?> name) {
		return new Follow(name.getQualifiedName(), null);
	}

	// -------------------------------------------------------------------------
	// Row3 type methods
	// -------------------------------------------------------------------------

	@Override
	public Row3<Long, Long, Long> fieldsRow() {
		return (Row3) super.fieldsRow();
	}

	/**
	 * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
	 */
	public <U> SelectField<U> mapping(Function3<? super Long, ? super Long, ? super Long, ? extends U> from) {
		return convertFrom(Records.mapping(from));
	}

	/**
	 * Convenience mapping calling {@link SelectField#convertFrom(Class, Function)}.
	 */
	public <U> SelectField<U> mapping(Class<U> toType,
			Function3<? super Long, ? super Long, ? super Long, ? extends U> from) {
		return convertFrom(toType, Records.mapping(from));
	}
}
