/*
 * This file is generated by jOOQ.
 */
package ch.rasc.realworld.db.tables;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import ch.rasc.realworld.db.DefaultSchema;
import ch.rasc.realworld.db.Indexes;
import ch.rasc.realworld.db.Keys;
import ch.rasc.realworld.db.tables.records.FollowRecord;

/**
 * This class is generated by jOOQ.
 */
@Generated(value = { "http://www.jooq.org", "jOOQ version:3.11.11" },
		comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Follow extends TableImpl<FollowRecord> {

	private static final long serialVersionUID = -23068414;

	/**
	 * The reference instance of <code>FOLLOW</code>
	 */
	public static final Follow FOLLOW = new Follow();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<FollowRecord> getRecordType() {
		return FollowRecord.class;
	}

	/**
	 * The column <code>FOLLOW.USER_ID</code>.
	 */
	public final TableField<FollowRecord, Long> USER_ID = createField("USER_ID",
			org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>FOLLOW.FOLLOW_ID</code>.
	 */
	public final TableField<FollowRecord, Long> FOLLOW_ID = createField("FOLLOW_ID",
			org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * Create a <code>FOLLOW</code> table reference
	 */
	public Follow() {
		this(DSL.name("FOLLOW"), null);
	}

	/**
	 * Create an aliased <code>FOLLOW</code> table reference
	 */
	public Follow(String alias) {
		this(DSL.name(alias), FOLLOW);
	}

	/**
	 * Create an aliased <code>FOLLOW</code> table reference
	 */
	public Follow(Name alias) {
		this(alias, FOLLOW);
	}

	private Follow(Name alias, Table<FollowRecord> aliased) {
		this(alias, aliased, null);
	}

	private Follow(Name alias, Table<FollowRecord> aliased, Field<?>[] parameters) {
		super(alias, null, aliased, parameters, DSL.comment(""));
	}

	public <O extends Record> Follow(Table<O> child, ForeignKey<O, FollowRecord> key) {
		super(child, key, FOLLOW);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Schema getSchema() {
		return DefaultSchema.DEFAULT_SCHEMA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<Index> getIndexes() {
		return Arrays.<Index>asList(Indexes.CONSTRAINT_INDEX_7B,
				Indexes.CONSTRAINT_INDEX_7BF, Indexes.PRIMARY_KEY_7B);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<FollowRecord> getPrimaryKey() {
		return Keys.CONSTRAINT_7B;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<FollowRecord>> getKeys() {
		return Arrays.<UniqueKey<FollowRecord>>asList(Keys.CONSTRAINT_7B);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<FollowRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<FollowRecord, ?>>asList(Keys.CONSTRAINT_7BF,
				Keys.CONSTRAINT_7BF0);
	}

	public AppUser constraint_7bf() {
		return new AppUser(this, Keys.CONSTRAINT_7BF);
	}

	public AppUser constraint_7bf0() {
		return new AppUser(this, Keys.CONSTRAINT_7BF0);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Follow as(String alias) {
		return new Follow(DSL.name(alias), this);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Follow as(Name alias) {
		return new Follow(alias, this);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Follow rename(String name) {
		return new Follow(DSL.name(name), null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Follow rename(Name name) {
		return new Follow(name, null);
	}
}
