/*
 * This file is generated by jOOQ.
 */
package ch.rasc.realworld.db.tables.records;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;

import ch.rasc.realworld.db.tables.AppUser;

/**
 * This class is generated by jOOQ.
 */
@Generated(value = { "http://www.jooq.org", "jOOQ version:3.11.11" },
		comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AppUserRecord extends UpdatableRecordImpl<AppUserRecord>
		implements Record6<Long, String, String, String, String, String> {

	private static final long serialVersionUID = 1729529748;

	/**
	 * Setter for <code>APP_USER.ID</code>.
	 */
	public void setId(Long value) {
		set(0, value);
	}

	/**
	 * Getter for <code>APP_USER.ID</code>.
	 */
	public Long getId() {
		return (Long) get(0);
	}

	/**
	 * Setter for <code>APP_USER.USERNAME</code>.
	 */
	public void setUsername(String value) {
		set(1, value);
	}

	/**
	 * Getter for <code>APP_USER.USERNAME</code>.
	 */
	public String getUsername() {
		return (String) get(1);
	}

	/**
	 * Setter for <code>APP_USER.PASSWORD</code>.
	 */
	public void setPassword(String value) {
		set(2, value);
	}

	/**
	 * Getter for <code>APP_USER.PASSWORD</code>.
	 */
	public String getPassword() {
		return (String) get(2);
	}

	/**
	 * Setter for <code>APP_USER.EMAIL</code>.
	 */
	public void setEmail(String value) {
		set(3, value);
	}

	/**
	 * Getter for <code>APP_USER.EMAIL</code>.
	 */
	public String getEmail() {
		return (String) get(3);
	}

	/**
	 * Setter for <code>APP_USER.BIO</code>.
	 */
	public void setBio(String value) {
		set(4, value);
	}

	/**
	 * Getter for <code>APP_USER.BIO</code>.
	 */
	public String getBio() {
		return (String) get(4);
	}

	/**
	 * Setter for <code>APP_USER.IMAGE</code>.
	 */
	public void setImage(String value) {
		set(5, value);
	}

	/**
	 * Getter for <code>APP_USER.IMAGE</code>.
	 */
	public String getImage() {
		return (String) get(5);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Long> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row6<Long, String, String, String, String, String> fieldsRow() {
		return (Row6) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row6<Long, String, String, String, String, String> valuesRow() {
		return (Row6) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field1() {
		return AppUser.APP_USER.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return AppUser.APP_USER.USERNAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return AppUser.APP_USER.PASSWORD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return AppUser.APP_USER.EMAIL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return AppUser.APP_USER.BIO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field6() {
		return AppUser.APP_USER.IMAGE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long component1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String component2() {
		return getUsername();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String component3() {
		return getPassword();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String component4() {
		return getEmail();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String component5() {
		return getBio();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String component6() {
		return getImage();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getUsername();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getPassword();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getEmail();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getBio();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value6() {
		return getImage();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AppUserRecord value1(Long value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AppUserRecord value2(String value) {
		setUsername(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AppUserRecord value3(String value) {
		setPassword(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AppUserRecord value4(String value) {
		setEmail(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AppUserRecord value5(String value) {
		setBio(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AppUserRecord value6(String value) {
		setImage(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AppUserRecord values(Long value1, String value2, String value3, String value4,
			String value5, String value6) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached AppUserRecord
	 */
	public AppUserRecord() {
		super(AppUser.APP_USER);
	}

	/**
	 * Create a detached, initialised AppUserRecord
	 */
	public AppUserRecord(Long id, String username, String password, String email,
			String bio, String image) {
		super(AppUser.APP_USER);

		set(0, id);
		set(1, username);
		set(2, password);
		set(3, email);
		set(4, bio);
		set(5, image);
	}
}
