/*
 * This file is generated by jOOQ.
 */
package ch.rasc.realworld.db.tables.records;


import ch.rasc.realworld.db.tables.ArticleFavorite;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ArticleFavoriteRecord extends UpdatableRecordImpl<ArticleFavoriteRecord> implements Record3<Long, Long, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>article_favorite.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>article_favorite.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>article_favorite.article_id</code>.
     */
    public void setArticleId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>article_favorite.article_id</code>.
     */
    public Long getArticleId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>article_favorite.user_id</code>.
     */
    public void setUserId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>article_favorite.user_id</code>.
     */
    public Long getUserId() {
        return (Long) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Long, Long, Long> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Long, Long, Long> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return ArticleFavorite.ARTICLE_FAVORITE.ID;
    }

    @Override
    public Field<Long> field2() {
        return ArticleFavorite.ARTICLE_FAVORITE.ARTICLE_ID;
    }

    @Override
    public Field<Long> field3() {
        return ArticleFavorite.ARTICLE_FAVORITE.USER_ID;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getArticleId();
    }

    @Override
    public Long component3() {
        return getUserId();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getArticleId();
    }

    @Override
    public Long value3() {
        return getUserId();
    }

    @Override
    public ArticleFavoriteRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public ArticleFavoriteRecord value2(Long value) {
        setArticleId(value);
        return this;
    }

    @Override
    public ArticleFavoriteRecord value3(Long value) {
        setUserId(value);
        return this;
    }

    @Override
    public ArticleFavoriteRecord values(Long value1, Long value2, Long value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ArticleFavoriteRecord
     */
    public ArticleFavoriteRecord() {
        super(ArticleFavorite.ARTICLE_FAVORITE);
    }

    /**
     * Create a detached, initialised ArticleFavoriteRecord
     */
    public ArticleFavoriteRecord(Long id, Long articleId, Long userId) {
        super(ArticleFavorite.ARTICLE_FAVORITE);

        setId(id);
        setArticleId(articleId);
        setUserId(userId);
    }
}
