/*
 * This file is generated by jOOQ.
 */
package ch.rasc.realworld.db.tables.records;

import java.time.OffsetDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;

import ch.rasc.realworld.db.tables.Article;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ArticleRecord extends UpdatableRecordImpl<ArticleRecord>
		implements Record8<Long, Long, String, String, String, String, OffsetDateTime, OffsetDateTime> {

	private static final long serialVersionUID = 1L;

	/**
	 * Setter for <code>article.id</code>.
	 */
	public void setId(Long value) {
		set(0, value);
	}

	/**
	 * Getter for <code>article.id</code>.
	 */
	public Long getId() {
		return (Long) get(0);
	}

	/**
	 * Setter for <code>article.user_id</code>.
	 */
	public void setUserId(Long value) {
		set(1, value);
	}

	/**
	 * Getter for <code>article.user_id</code>.
	 */
	public Long getUserId() {
		return (Long) get(1);
	}

	/**
	 * Setter for <code>article.slug</code>.
	 */
	public void setSlug(String value) {
		set(2, value);
	}

	/**
	 * Getter for <code>article.slug</code>.
	 */
	public String getSlug() {
		return (String) get(2);
	}

	/**
	 * Setter for <code>article.title</code>.
	 */
	public void setTitle(String value) {
		set(3, value);
	}

	/**
	 * Getter for <code>article.title</code>.
	 */
	public String getTitle() {
		return (String) get(3);
	}

	/**
	 * Setter for <code>article.description</code>.
	 */
	public void setDescription(String value) {
		set(4, value);
	}

	/**
	 * Getter for <code>article.description</code>.
	 */
	public String getDescription() {
		return (String) get(4);
	}

	/**
	 * Setter for <code>article.body</code>.
	 */
	public void setBody(String value) {
		set(5, value);
	}

	/**
	 * Getter for <code>article.body</code>.
	 */
	public String getBody() {
		return (String) get(5);
	}

	/**
	 * Setter for <code>article.created_at</code>.
	 */
	public void setCreatedAt(OffsetDateTime value) {
		set(6, value);
	}

	/**
	 * Getter for <code>article.created_at</code>.
	 */
	public OffsetDateTime getCreatedAt() {
		return (OffsetDateTime) get(6);
	}

	/**
	 * Setter for <code>article.updated_at</code>.
	 */
	public void setUpdatedAt(OffsetDateTime value) {
		set(7, value);
	}

	/**
	 * Getter for <code>article.updated_at</code>.
	 */
	public OffsetDateTime getUpdatedAt() {
		return (OffsetDateTime) get(7);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	@Override
	public Record1<Long> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record8 type implementation
	// -------------------------------------------------------------------------

	@Override
	public Row8<Long, Long, String, String, String, String, OffsetDateTime, OffsetDateTime> fieldsRow() {
		return (Row8) super.fieldsRow();
	}

	@Override
	public Row8<Long, Long, String, String, String, String, OffsetDateTime, OffsetDateTime> valuesRow() {
		return (Row8) super.valuesRow();
	}

	@Override
	public Field<Long> field1() {
		return Article.ARTICLE.ID;
	}

	@Override
	public Field<Long> field2() {
		return Article.ARTICLE.USER_ID;
	}

	@Override
	public Field<String> field3() {
		return Article.ARTICLE.SLUG;
	}

	@Override
	public Field<String> field4() {
		return Article.ARTICLE.TITLE;
	}

	@Override
	public Field<String> field5() {
		return Article.ARTICLE.DESCRIPTION;
	}

	@Override
	public Field<String> field6() {
		return Article.ARTICLE.BODY;
	}

	@Override
	public Field<OffsetDateTime> field7() {
		return Article.ARTICLE.CREATED_AT;
	}

	@Override
	public Field<OffsetDateTime> field8() {
		return Article.ARTICLE.UPDATED_AT;
	}

	@Override
	public Long component1() {
		return getId();
	}

	@Override
	public Long component2() {
		return getUserId();
	}

	@Override
	public String component3() {
		return getSlug();
	}

	@Override
	public String component4() {
		return getTitle();
	}

	@Override
	public String component5() {
		return getDescription();
	}

	@Override
	public String component6() {
		return getBody();
	}

	@Override
	public OffsetDateTime component7() {
		return getCreatedAt();
	}

	@Override
	public OffsetDateTime component8() {
		return getUpdatedAt();
	}

	@Override
	public Long value1() {
		return getId();
	}

	@Override
	public Long value2() {
		return getUserId();
	}

	@Override
	public String value3() {
		return getSlug();
	}

	@Override
	public String value4() {
		return getTitle();
	}

	@Override
	public String value5() {
		return getDescription();
	}

	@Override
	public String value6() {
		return getBody();
	}

	@Override
	public OffsetDateTime value7() {
		return getCreatedAt();
	}

	@Override
	public OffsetDateTime value8() {
		return getUpdatedAt();
	}

	@Override
	public ArticleRecord value1(Long value) {
		setId(value);
		return this;
	}

	@Override
	public ArticleRecord value2(Long value) {
		setUserId(value);
		return this;
	}

	@Override
	public ArticleRecord value3(String value) {
		setSlug(value);
		return this;
	}

	@Override
	public ArticleRecord value4(String value) {
		setTitle(value);
		return this;
	}

	@Override
	public ArticleRecord value5(String value) {
		setDescription(value);
		return this;
	}

	@Override
	public ArticleRecord value6(String value) {
		setBody(value);
		return this;
	}

	@Override
	public ArticleRecord value7(OffsetDateTime value) {
		setCreatedAt(value);
		return this;
	}

	@Override
	public ArticleRecord value8(OffsetDateTime value) {
		setUpdatedAt(value);
		return this;
	}

	@Override
	public ArticleRecord values(Long value1, Long value2, String value3, String value4, String value5, String value6,
			OffsetDateTime value7, OffsetDateTime value8) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ArticleRecord
	 */
	public ArticleRecord() {
		super(Article.ARTICLE);
	}

	/**
	 * Create a detached, initialised ArticleRecord
	 */
	public ArticleRecord(Long id, Long userId, String slug, String title, String description, String body,
			OffsetDateTime createdAt, OffsetDateTime updatedAt) {
		super(Article.ARTICLE);

		setId(id);
		setUserId(userId);
		setSlug(slug);
		setTitle(title);
		setDescription(description);
		setBody(body);
		setCreatedAt(createdAt);
		setUpdatedAt(updatedAt);
	}
}
