/*
 * This file is generated by jOOQ.
 */
package ch.rasc.realworld.db.tables.records;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;

import ch.rasc.realworld.db.tables.ArticleFavorite;

/**
 * This class is generated by jOOQ.
 */
@Generated(value = { "http://www.jooq.org", "jOOQ version:3.11.11" },
		comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ArticleFavoriteRecord extends UpdatableRecordImpl<ArticleFavoriteRecord>
		implements Record2<Long, Long> {

	private static final long serialVersionUID = 559616451;

	/**
	 * Setter for <code>ARTICLE_FAVORITE.ARTICLE_ID</code>.
	 */
	public void setArticleId(Long value) {
		set(0, value);
	}

	/**
	 * Getter for <code>ARTICLE_FAVORITE.ARTICLE_ID</code>.
	 */
	public Long getArticleId() {
		return (Long) get(0);
	}

	/**
	 * Setter for <code>ARTICLE_FAVORITE.USER_ID</code>.
	 */
	public void setUserId(Long value) {
		set(1, value);
	}

	/**
	 * Getter for <code>ARTICLE_FAVORITE.USER_ID</code>.
	 */
	public Long getUserId() {
		return (Long) get(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record2<Long, Long> key() {
		return (Record2) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<Long, Long> fieldsRow() {
		return (Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<Long, Long> valuesRow() {
		return (Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field1() {
		return ArticleFavorite.ARTICLE_FAVORITE.ARTICLE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field2() {
		return ArticleFavorite.ARTICLE_FAVORITE.USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long component1() {
		return getArticleId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long component2() {
		return getUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value1() {
		return getArticleId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value2() {
		return getUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ArticleFavoriteRecord value1(Long value) {
		setArticleId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ArticleFavoriteRecord value2(Long value) {
		setUserId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ArticleFavoriteRecord values(Long value1, Long value2) {
		value1(value1);
		value2(value2);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ArticleFavoriteRecord
	 */
	public ArticleFavoriteRecord() {
		super(ArticleFavorite.ARTICLE_FAVORITE);
	}

	/**
	 * Create a detached, initialised ArticleFavoriteRecord
	 */
	public ArticleFavoriteRecord(Long articleId, Long userId) {
		super(ArticleFavorite.ARTICLE_FAVORITE);

		set(0, articleId);
		set(1, userId);
	}
}
