/*
 * This file is generated by jOOQ.
 */
package ch.rasc.realworld.db.tables.records;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

import ch.rasc.realworld.db.tables.Follow;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FollowRecord extends UpdatableRecordImpl<FollowRecord> implements Record3<Long, Long, Long> {

	private static final long serialVersionUID = 1L;

	/**
	 * Setter for <code>follow.id</code>.
	 */
	public void setId(Long value) {
		set(0, value);
	}

	/**
	 * Getter for <code>follow.id</code>.
	 */
	public Long getId() {
		return (Long) get(0);
	}

	/**
	 * Setter for <code>follow.user_id</code>.
	 */
	public void setUserId(Long value) {
		set(1, value);
	}

	/**
	 * Getter for <code>follow.user_id</code>.
	 */
	public Long getUserId() {
		return (Long) get(1);
	}

	/**
	 * Setter for <code>follow.follow_id</code>.
	 */
	public void setFollowId(Long value) {
		set(2, value);
	}

	/**
	 * Getter for <code>follow.follow_id</code>.
	 */
	public Long getFollowId() {
		return (Long) get(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	@Override
	public Record1<Long> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	@Override
	public Row3<Long, Long, Long> fieldsRow() {
		return (Row3) super.fieldsRow();
	}

	@Override
	public Row3<Long, Long, Long> valuesRow() {
		return (Row3) super.valuesRow();
	}

	@Override
	public Field<Long> field1() {
		return Follow.FOLLOW.ID;
	}

	@Override
	public Field<Long> field2() {
		return Follow.FOLLOW.USER_ID;
	}

	@Override
	public Field<Long> field3() {
		return Follow.FOLLOW.FOLLOW_ID;
	}

	@Override
	public Long component1() {
		return getId();
	}

	@Override
	public Long component2() {
		return getUserId();
	}

	@Override
	public Long component3() {
		return getFollowId();
	}

	@Override
	public Long value1() {
		return getId();
	}

	@Override
	public Long value2() {
		return getUserId();
	}

	@Override
	public Long value3() {
		return getFollowId();
	}

	@Override
	public FollowRecord value1(Long value) {
		setId(value);
		return this;
	}

	@Override
	public FollowRecord value2(Long value) {
		setUserId(value);
		return this;
	}

	@Override
	public FollowRecord value3(Long value) {
		setFollowId(value);
		return this;
	}

	@Override
	public FollowRecord values(Long value1, Long value2, Long value3) {
		value1(value1);
		value2(value2);
		value3(value3);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached FollowRecord
	 */
	public FollowRecord() {
		super(Follow.FOLLOW);
	}

	/**
	 * Create a detached, initialised FollowRecord
	 */
	public FollowRecord(Long id, Long userId, Long followId) {
		super(Follow.FOLLOW);

		setId(id);
		setUserId(userId);
		setFollowId(followId);
	}
}
